semtag is now reltag. semtag is refactored to ONLY TAG and PUSH, not release.

diff --git a/.local/bin/semtag b/.local/bin/semtag
--- a/.local/bin/semtag
+++ b/.local/bin/semtag
@@ -16,30 +16,14 @@ function usage {
 function check_bump_set {
   if [[ "${BUMP_TYPE}x" != "x" ]]; then
     # BUMP_TYPE already set
-    if [[ ${BUMP_TYPE} == "chef" ]]; then
-      echo "tag is automatically set to match chef cookbook version ${chef_tag}"
-      return 1
-    else
-      echo "Only one option at a time is supported."
-      usage
-    fi
+    echo "Only one option at a time is supported."
+    usage
   fi
 }
 
-command -v gh >/dev/null 2>&1 || {
-  echo >&2 "gh (https://cli.github.com/) needs to be installed."
-  exit 1
-}
+CURRENT_RELEASE=$(gh release list --exclude-drafts --limit 1 | cut -f3 | sed 's/v//')
 
-if [[ -a ./metadata.rb ]]; then
-  cookbook_version=$(grep -w '^version' metadata.rb |awk '{print $2}' | tr -C -d "v[:digit:].")
-  chef_tag="v${cookbook_version}"
-  BUMP_TYPE="chef"
-else
-  CURRENT_RELEASE=$(gh release list --exclude-drafts --limit 1 | cut -f3 | sed 's/v//')
-fi
-
-if [[ ${#} -eq 0 && -z "${chef_tag}" && ! -z "${CURRENT_RELEASE}" ]]; then
+if [[ ${#} -eq 0 && -n "${CURRENT_RELEASE}" ]]; then
    usage
 fi
 
@@ -60,25 +44,22 @@ while getopts ${optstring} arg; do
   esac
 done
 
-if [[ ${BUMP_TYPE} == "chef" ]]; then
-  NEW_RELEASE="${chef_tag}"
+if [[ "${CURRENT_RELEASE}x" == "x" ]]; then
+  NEW_RELEASE="v1.0.0"
 else
-  if [[ "${CURRENT_RELEASE}x" == "x" ]]; then
-    NEW_RELEASE="v1.0.0"
-  else
-    IFS='.' read -r major minor patch <<< $CURRENT_RELEASE
+  IFS='.' read -r major minor patch <<< $CURRENT_RELEASE
 
-    case "${BUMP_TYPE}" in
-      major) major=$((major+1)); minor=0; patch=0 ;;
-      minor) minor=$((minor+1)); patch=0 ;;
-      patch) patch=$((patch+1)) ;;
-      *)
-        echo >&2 "Somehow we got an invalid release type of ${BUMP_TYPE}"
-        exit 1
-        ;;
-    esac
+  case "${BUMP_TYPE}" in
+    major) major=$((major+1)); minor=0; patch=0 ;;
+    minor) minor=$((minor+1)); patch=0 ;;
+    patch) patch=$((patch+1)) ;;
+    *)
+      echo >&2 "Somehow we got an invalid release type of ${BUMP_TYPE}"
+      exit 1
+      ;;
+  esac
 
-    NEW_RELEASE="v${major}.${minor}.${patch}"
-  fi
+  NEW_RELEASE="v${major}.${minor}.${patch}"
 fi
-exec gh release create $NEW_RELEASE --generate-notes
+git tag $NEW_RELEASE
+git push origin $NEW_RELEASE
